package bizplugin

// ============================================================
// 编程答题题库
// ============================================================

// quizLanguage 是题库内部使用的编程语言标识。
type quizLanguage string

const (
	quizLanguageJava   quizLanguage = "java"
	quizLanguageGo     quizLanguage = "go"
	quizLanguagePython quizLanguage = "python"
	quizLanguageC      quizLanguage = "c"
	quizLanguageCPP    quizLanguage = "cpp"
)

// allQuizLanguages 按帮助文案中的固定顺序列出当前支持的语言。
var allQuizLanguages = []quizLanguage{
	quizLanguageJava,
	quizLanguageGo,
	quizLanguagePython,
	quizLanguageC,
	quizLanguageCPP,
}

// String 返回适合展示给玩家的语言名称。
func (language quizLanguage) String() string {
	switch language {
	case quizLanguageJava:
		return "Java"
	case quizLanguageGo:
		return "Go"
	case quizLanguagePython:
		return "Python"
	case quizLanguageC:
		return "C"
	case quizLanguageCPP:
		return "C++"
	default:
		return "未知语言"
	}
}

// quizQuestion 是一道固定四选一的新手编程题。
// AnswerIndex 使用 0～3，依次对应 A～D。
type quizQuestion struct {
	ID          string       `json:"id"`
	Language    quizLanguage `json:"language"`
	Prompt      string       `json:"prompt"`
	Options     [4]string    `json:"options"`
	AnswerIndex int          `json:"answer_index"`
	Explanation string       `json:"explanation"`
}

// quizQuestionBank 是项目内置的原创中文新手题库。
// 每门语言至少提供30道题，单轮从所选语言中抽取五道且不重复。
var quizQuestionBank = map[quizLanguage][]quizQuestion{
	quizLanguageJava: {
		{
			ID:          "java-001",
			Language:    quizLanguageJava,
			Prompt:      "在 Java 中，哪一行代码可以输出一行文字？",
			Options:     [4]string{"System.out.println(\"Hello\");", "print(\"Hello\")", "fmt.Println(\"Hello\")", "printf(\"Hello\")"},
			AnswerIndex: 0,
			Explanation: "Java 常用 System.out.println 输出一行内容。",
		},
		{
			ID:          "java-002",
			Language:    quizLanguageJava,
			Prompt:      "下面哪个是常见的 Java 程序入口方法？",
			Options:     [4]string{"func main()", "public static void main(String[] args)", "int main()", "def main():"},
			AnswerIndex: 1,
			Explanation: "Java 应用通常从 public static void main(String[] args) 开始执行。",
		},
		{
			ID:          "java-003",
			Language:    quizLanguageJava,
			Prompt:      "Java 表达式 2 + 3 * 2 的结果是多少？",
			Options:     [4]string{"10", "12", "8", "7"},
			AnswerIndex: 2,
			Explanation: "乘法优先于加法，所以先算 3 * 2，再加 2，结果为 8。",
		},
		{
			ID:          "java-004",
			Language:    quizLanguageJava,
			Prompt:      "若 int[] numbers = {10, 20, 30};，怎样取得第一个元素？",
			Options:     [4]string{"numbers[1]", "numbers.first()", "numbers(0)", "numbers[0]"},
			AnswerIndex: 3,
			Explanation: "Java 数组下标从 0 开始，第一个元素是 numbers[0]。",
		},
		{
			ID:          "java-005",
			Language:    quizLanguageJava,
			Prompt:      "在 Java 中，通常用哪个方法比较两个字符串的内容是否相同？",
			Options:     [4]string{"equals()", "same()", "compareText()", "match()"},
			AnswerIndex: 0,
			Explanation: "字符串内容比较通常使用 equals 方法。",
		},
		{
			ID:          "java-006",
			Language:    quizLanguageJava,
			Prompt:      "Java 中表示逻辑“并且”的运算符是哪一个？",
			Options:     [4]string{"||", "&&", "!", "=="},
			AnswerIndex: 1,
			Explanation: "&& 只有在左右两个条件都为 true 时才得到 true。",
		},
		{
			ID:          "java-007",
			Language:    quizLanguageJava,
			Prompt:      "下面循环会依次输出什么？\nfor (int i = 0; i < 3; i++) {\n    System.out.print(i);\n}",
			Options:     [4]string{"123", "0123", "012", "321"},
			AnswerIndex: 2,
			Explanation: "i 从 0 开始，在 i 等于 3 前停止，因此输出 012。",
		},
		{
			ID:          "java-008",
			Language:    quizLanguageJava,
			Prompt:      "已有 class Student {}，哪一项可以创建一个 Student 对象？",
			Options:     [4]string{"Student.create()", "Student()", "create Student", "new Student()"},
			AnswerIndex: 3,
			Explanation: "Java 使用 new 调用构造方法创建对象。",
		},
		{
			ID:          "java-009",
			Language:    quizLanguageJava,
			Prompt:      "执行 int x = 5; x++; 后，x 的值是多少？",
			Options:     [4]string{"6", "4", "5", "55"},
			AnswerIndex: 0,
			Explanation: "++ 会让整数变量的值增加 1。",
		},
		{
			ID:          "java-010",
			Language:    quizLanguageJava,
			Prompt:      "Java 中适合保存 true 或 false 的基本类型是什么？",
			Options:     [4]string{"int", "boolean", "String", "char"},
			AnswerIndex: 1,
			Explanation: "boolean 类型只有 true 和 false 两种取值。",
		},
		{
			ID:          "java-011",
			Language:    quizLanguageJava,
			Prompt:      "下面哪一项声明了 int 变量 score，并将它初始化为 100？",
			Options:     [4]string{"int score = 100;", "score := 100", "integer score = 100;", "var score: int = 100;"},
			AnswerIndex: 0,
			Explanation: "Java 使用“类型 变量名 = 值;”的形式声明并初始化变量。",
		},
		{
			ID:          "java-012",
			Language:    quizLanguageJava,
			Prompt:      "执行 String text = \"Java\"; 后，表达式 text + 8 的结果是什么？",
			Options:     [4]string{"12", "Java8", "8Java", "编译错误"},
			AnswerIndex: 1,
			Explanation: "字符串与整数使用 + 连接时，整数会转成文字，因此结果是 Java8。",
		},
		{
			ID:          "java-013",
			Language:    quizLanguageJava,
			Prompt:      "哪一项是合法的 Java 条件判断写法？",
			Options:     [4]string{"if score >= 60 then {}", "when (score >= 60) {}", "if (score >= 60) {}", "if score >= 60: {}"},
			AnswerIndex: 2,
			Explanation: "Java 的 if 条件写在圆括号中，代码块通常写在花括号中。",
		},
		{
			ID:          "java-014",
			Language:    quizLanguageJava,
			Prompt:      "Java 中哪个关键字可以在条件为 true 时重复执行代码块？",
			Options:     [4]string{"repeat", "loop", "until", "while"},
			AnswerIndex: 3,
			Explanation: "while 会在条件为 true 时重复执行它的代码块。",
		},
		{
			ID:          "java-015",
			Language:    quizLanguageJava,
			Prompt:      "已有 int[] numbers = {4, 5, 6};，怎样取得数组长度？",
			Options:     [4]string{"numbers.length", "numbers.length()", "len(numbers)", "numbers.size()"},
			AnswerIndex: 0,
			Explanation: "Java 数组通过 length 字段取得长度，不需要加圆括号。",
		},
		{
			ID:          "java-016",
			Language:    quizLanguageJava,
			Prompt:      "表达式 \"Lanmei\".length() 的结果是多少？",
			Options:     [4]string{"5", "6", "7", "8"},
			AnswerIndex: 1,
			Explanation: "字符串 Lanmei 包含 6 个字符，因此 length() 返回 6。",
		},
		{
			ID:          "java-017",
			Language:    quizLanguageJava,
			Prompt:      "哪一项可以把字符串 \"42\" 转换为 int 值 42？",
			Options:     [4]string{"int(\"42\")", "String.toInt(\"42\")", "Integer.parseInt(\"42\")", "parse(\"42\")"},
			AnswerIndex: 2,
			Explanation: "Integer.parseInt 可以把符合整数格式的字符串转换为 int。",
		},
		{
			ID:          "java-018",
			Language:    quizLanguageJava,
			Prompt:      "已有 ArrayList<String> names = new ArrayList<>();，怎样添加元素 \"蓝妹\"？",
			Options:     [4]string{"names.push(\"蓝妹\");", "names.append(\"蓝妹\");", "add(names, \"蓝妹\");", "names.add(\"蓝妹\");"},
			AnswerIndex: 3,
			Explanation: "ArrayList 的 add 方法用于添加元素。",
		},
		{
			ID:          "java-019",
			Language:    quizLanguageJava,
			Prompt:      "执行 final int level = 1; 后，下面哪种说法正确？",
			Options:     [4]string{"level 之后不能再次被赋值", "level 会自动变成 2", "level 只能在循环中使用", "level 的类型变成 String"},
			AnswerIndex: 0,
			Explanation: "final 变量完成赋值后不能再被重新赋值。",
		},
		{
			ID:          "java-020",
			Language:    quizLanguageJava,
			Prompt:      "Java 中哪个访问修饰符通常提供最宽的可见范围？",
			Options:     [4]string{"private", "public", "protected", "final"},
			AnswerIndex: 1,
			Explanation: "public 成员通常可以被其他类访问。",
		},
		{
			ID:          "java-021",
			Language:    quizLanguageJava,
			Prompt:      "哪一项定义了一个返回两个 int 之和的静态方法？",
			Options:     [4]string{"func add(a int, b int) int { return a + b; }", "static add(int a, int b) { a + b; }", "static int add(int a, int b) { return a + b; }", "def add(a, b): return a + b"},
			AnswerIndex: 2,
			Explanation: "Java 方法要写返回类型、方法名、参数和方法体，并用 return 返回结果。",
		},
		{
			ID:          "java-022",
			Language:    quizLanguageJava,
			Prompt:      "Java 表达式 17 % 5 的结果是多少？",
			Options:     [4]string{"0", "3", "3.4", "2"},
			AnswerIndex: 3,
			Explanation: "% 计算整数除法的余数，17 除以 5 的余数是 2。",
		},
		{
			ID:          "java-023",
			Language:    quizLanguageJava,
			Prompt:      "下面哪一项正确声明了字符变量 grade？",
			Options:     [4]string{"char grade = 'A';", "char grade = \"A\";", "character grade = 'A';", "String grade = 'A';"},
			AnswerIndex: 0,
			Explanation: "Java 的 char 字面量使用单引号，例如 'A'。",
		},
		{
			ID:          "java-024",
			Language:    quizLanguageJava,
			Prompt:      "下面哪一项可以保存小数 19.5？",
			Options:     [4]string{"int price = 19.5;", "double price = 19.5;", "boolean price = 19.5;", "char price = 19.5;"},
			AnswerIndex: 1,
			Explanation: "double 是 Java 中常用的浮点数基本类型，可以保存 19.5。",
		},
		{
			ID:          "java-025",
			Language:    quizLanguageJava,
			Prompt:      "Java 引用变量的值为 null，通常表示什么？",
			Options:     [4]string{"它保存数字 0", "它保存空字符串", "它当前没有指向对象", "它一定指向新对象"},
			AnswerIndex: 2,
			Explanation: "null 表示引用当前没有指向任何对象。",
		},
		{
			ID:          "java-026",
			Language:    quizLanguageJava,
			Prompt:      "Java 中通常用哪组关键字捕获并处理异常？",
			Options:     [4]string{"if 和 else", "switch 和 case", "check 和 handle", "try 和 catch"},
			AnswerIndex: 3,
			Explanation: "可能抛出异常的代码放在 try 中，异常处理代码写在 catch 中。",
		},
		{
			ID:          "java-027",
			Language:    quizLanguageJava,
			Prompt:      "在传统的 switch case: 写法中，break 通常有什么作用？",
			Options:     [4]string{"结束当前 switch 分支", "重新执行当前分支", "声明一个变量", "比较两个字符串"},
			AnswerIndex: 0,
			Explanation: "break 会结束当前 switch，避免继续执行后续 case。",
		},
		{
			ID:          "java-028",
			Language:    quizLanguageJava,
			Prompt:      "若 Dog 类要继承 Animal 类，应使用哪个关键字？",
			Options:     [4]string{"implements", "extends", "inherits", "superclass"},
			AnswerIndex: 1,
			Explanation: "Java 类使用 extends 继承另一个类。",
		},
		{
			ID:          "java-029",
			Language:    quizLanguageJava,
			Prompt:      "若 Bird 类要实现 Flyable 接口，应使用哪个关键字？",
			Options:     [4]string{"extends", "interface", "implements", "instanceof"},
			AnswerIndex: 2,
			Explanation: "Java 类使用 implements 声明它实现某个接口。",
		},
		{
			ID:          "java-030",
			Language:    quizLanguageJava,
			Prompt:      "Java 表达式 Math.max(4, 9) 的结果是多少？",
			Options:     [4]string{"4", "13", "36", "9"},
			AnswerIndex: 3,
			Explanation: "Math.max 返回两个参数中较大的一个，因此结果是 9。",
		},
	},
	quizLanguageGo: {
		{
			ID:          "go-001",
			Language:    quizLanguageGo,
			Prompt:      "可直接编译为可执行程序的 Go 源文件通常属于哪个包？",
			Options:     [4]string{"run", "main", "app", "start"},
			AnswerIndex: 1,
			Explanation: "Go 可执行程序使用 package main，并提供 main 函数。",
		},
		{
			ID:          "go-002",
			Language:    quizLanguageGo,
			Prompt:      "在 Go 函数内部，哪一项可以简短声明变量 name 并赋值为 \"蓝妹\"？",
			Options:     [4]string{"name := \"蓝妹\"", "string name = \"蓝妹\"", "let name = \"蓝妹\"", "name ::= \"蓝妹\""},
			AnswerIndex: 0,
			Explanation: ":= 可在 Go 函数内部声明并初始化变量。",
		},
		{
			ID:          "go-003",
			Language:    quizLanguageGo,
			Prompt:      "导入 fmt 包后，哪一项可以输出一行文字？",
			Options:     [4]string{"fmt.PrintLine(\"Hi\")", "System.out.println(\"Hi\")", "fmt.Println(\"Hi\")", "console.log(\"Hi\")"},
			AnswerIndex: 2,
			Explanation: "fmt.Println 会输出参数并在末尾换行。",
		},
		{
			ID:          "go-004",
			Language:    quizLanguageGo,
			Prompt:      "Go 使用哪个关键字编写循环？",
			Options:     [4]string{"while", "loop", "repeat", "for"},
			AnswerIndex: 3,
			Explanation: "Go 只提供 for 这一种循环关键字。",
		},
		{
			ID:          "go-005",
			Language:    quizLanguageGo,
			Prompt:      "下面哪一项是包含 1、2、3 的 Go 整数切片字面量？",
			Options:     [4]string{"[]int{1, 2, 3}", "int[1, 2, 3]", "list<int>{1, 2, 3}", "[1, 2, 3]int"},
			AnswerIndex: 0,
			Explanation: "[]int{1, 2, 3} 会创建一个 int 切片。",
		},
		{
			ID:          "go-006",
			Language:    quizLanguageGo,
			Prompt:      "Go 中调用可能失败的函数后，最常见的错误检查条件是什么？",
			Options:     [4]string{"if error", "if err != nil", "catch err", "if err == true"},
			AnswerIndex: 1,
			Explanation: "Go 通常显式检查返回的 err 是否不为 nil。",
		},
		{
			ID:          "go-007",
			Language:    quizLanguageGo,
			Prompt:      "Go 数组和切片的第一个元素下标是多少？",
			Options:     [4]string{"-1", "1", "0", "由长度决定"},
			AnswerIndex: 2,
			Explanation: "Go 数组和切片都从下标 0 开始。",
		},
		{
			ID:          "go-008",
			Language:    quizLanguageGo,
			Prompt:      "执行 values := []string{\"a\", \"b\", \"c\"}; len(values) 的结果是什么？",
			Options:     [4]string{"2", "4", "0", "3"},
			AnswerIndex: 3,
			Explanation: "切片 values 中有三个元素，因此 len(values) 为 3。",
		},
		{
			ID:          "go-009",
			Language:    quizLanguageGo,
			Prompt:      "Go 中已声明的 int 变量未显式赋初值时，它的零值是什么？",
			Options:     [4]string{"0", "nil", "1", "未定义"},
			AnswerIndex: 0,
			Explanation: "Go 的整数类型零值为 0。",
		},
		{
			ID:          "go-010",
			Language:    quizLanguageGo,
			Prompt:      "Go 中用于按多个分支选择执行代码的关键字是什么？",
			Options:     [4]string{"selectOnly", "switch", "choose", "when"},
			AnswerIndex: 1,
			Explanation: "switch 用于根据表达式或条件选择分支。",
		},
		{
			ID:          "go-011",
			Language:    quizLanguageGo,
			Prompt:      "Go 中哪一项声明了值为 10 的常量 Max？",
			Options:     [4]string{"const Max = 10", "constant Max = 10", "final Max = 10", "let Max = 10"},
			AnswerIndex: 0,
			Explanation: "Go 使用 const 关键字声明常量。",
		},
		{
			ID:          "go-012",
			Language:    quizLanguageGo,
			Prompt:      "哪一项可以在 Go 的包级作用域声明 int 变量 age，并赋值为 18？",
			Options:     [4]string{"age := 18", "var age int = 18", "int age = 18", "let age: int = 18"},
			AnswerIndex: 1,
			Explanation: "包级变量使用 var 声明；简短声明 := 只能用在函数内部。",
		},
		{
			ID:          "go-013",
			Language:    quizLanguageGo,
			Prompt:      "哪一项定义了一个接收两个 int 并返回 int 的 Go 函数？",
			Options:     [4]string{"function add(a int, b int): int {}", "int add(int a, int b) {}", "func add(a int, b int) int {}", "def add(a: int, b: int) -> int:"},
			AnswerIndex: 2,
			Explanation: "Go 函数以 func 开头，返回类型写在参数列表之后。",
		},
		{
			ID:          "go-014",
			Language:    quizLanguageGo,
			Prompt:      "下面哪一项是返回 int 和 string 两个值的合法 Go 函数？",
			Options:     [4]string{"func pair() int, string { return 1, \"a\" }", "func pair() [int, string] { return 1, \"a\" }", "func pair() tuple { return 1, \"a\" }", "func pair() (int, string) { return 1, \"a\" }"},
			AnswerIndex: 3,
			Explanation: "Go 将多个返回类型写在圆括号中，并可一次返回多个值。",
		},
		{
			ID:          "go-015",
			Language:    quizLanguageGo,
			Prompt:      "下面哪一项是把字符串映射到整数的 Go map 字面量？",
			Options:     [4]string{"map[string]int{\"a\": 1}", "map<string, int>{\"a\": 1}", "{\"a\" = 1}", "dict[string]int{\"a\": 1}"},
			AnswerIndex: 0,
			Explanation: "map[string]int 表示键为 string、值为 int 的映射。",
		},
		{
			ID:          "go-016",
			Language:    quizLanguageGo,
			Prompt:      "已有 scores := map[string]int{\"蓝妹\": 10}，哪一项能同时取得值和键是否存在？",
			Options:     [4]string{"value := scores.get(\"蓝妹\")", "value, ok := scores[\"蓝妹\"]", "value, ok := scores.get(\"蓝妹\")", "ok, value := has(scores, \"蓝妹\")"},
			AnswerIndex: 1,
			Explanation: "读取 map 时可接收第二个布尔值，用来判断键是否存在。",
		},
		{
			ID:          "go-017",
			Language:    quizLanguageGo,
			Prompt:      "已有 values := []int{1, 2}，怎样把 3 添加到切片末尾并保存结果？",
			Options:     [4]string{"values.add(3)", "append(values, 3)", "values = append(values, 3)", "push(values, 3)"},
			AnswerIndex: 2,
			Explanation: "append 返回更新后的切片，因此通常要把结果重新赋给原变量。",
		},
		{
			ID:          "go-018",
			Language:    quizLanguageGo,
			Prompt:      "哪一项可以遍历切片 values，并同时取得下标 i 和元素 v？",
			Options:     [4]string{"for (i, v) in values {}", "foreach i, v in values {}", "for i, v of values {}", "for i, v := range values {}"},
			AnswerIndex: 3,
			Explanation: "Go 使用 for 和 range 遍历切片，range 可产生下标和值。",
		},
		{
			ID:          "go-019",
			Language:    quizLanguageGo,
			Prompt:      "在 Go 函数中写 defer cleanup()，cleanup 通常会在什么时候执行？",
			Options:     [4]string{"所在函数即将返回时", "程序编译之前", "每次循环开始时", "永远不会执行"},
			AnswerIndex: 0,
			Explanation: "defer 会把函数调用推迟到当前函数返回前执行。",
		},
		{
			ID:          "go-020",
			Language:    quizLanguageGo,
			Prompt:      "哪一项可以让 Go 函数 work 作为新的 goroutine 启动？",
			Options:     [4]string{"async work()", "go work()", "thread work()", "goroutine(work)"},
			AnswerIndex: 1,
			Explanation: "在函数调用前加 go，可以在新的 goroutine 中运行它。",
		},
		{
			ID:          "go-021",
			Language:    quizLanguageGo,
			Prompt:      "哪一项创建了一个传递 int 的 Go 通道？",
			Options:     [4]string{"ch := channel<int>()", "ch := new(channel int)", "ch := make(chan int)", "chan ch = int"},
			AnswerIndex: 2,
			Explanation: "make(chan int) 会创建一个可传递 int 值的通道。",
		},
		{
			ID:          "go-022",
			Language:    quizLanguageGo,
			Prompt:      "哪一项定义了包含 Name string 字段的 Go 结构体 Student？",
			Options:     [4]string{"class Student { Name string }", "struct Student(Name string)", "type Student class { Name string }", "type Student struct { Name string }"},
			AnswerIndex: 3,
			Explanation: "Go 使用 type 名称 struct 的形式定义结构体。",
		},
		{
			ID:          "go-023",
			Language:    quizLanguageGo,
			Prompt:      "Go 中若希望标识符可被其他包访问，它的名称通常应怎样书写？",
			Options:     [4]string{"首字母大写", "全部小写", "以数字开头", "以 @ 开头"},
			AnswerIndex: 0,
			Explanation: "Go 使用首字母大写表示导出的标识符，其他包可以访问它。",
		},
		{
			ID:          "go-024",
			Language:    quizLanguageGo,
			Prompt:      "已有 p := &number，哪个表达式可以取得 p 指向的值？",
			Options:     [4]string{"&p", "*p", "p.value", "value(p)"},
			AnswerIndex: 1,
			Explanation: "对指针使用 * 可以取得它指向的值。",
		},
		{
			ID:          "go-025",
			Language:    quizLanguageGo,
			Prompt:      "已有整数变量 n，哪一项可以把它显式转换为 float64？",
			Options:     [4]string{"n.toFloat64()", "(float64)n", "float64(n)", "cast<float64>(n)"},
			AnswerIndex: 2,
			Explanation: "Go 使用目标类型加圆括号的形式进行显式类型转换。",
		},
		{
			ID:          "go-026",
			Language:    quizLanguageGo,
			Prompt:      "Go 中通常使用哪种类型表示一个 Unicode 码点？",
			Options:     [4]string{"string", "byte", "char", "rune"},
			AnswerIndex: 3,
			Explanation: "rune 是 int32 的别名，通常用于表示 Unicode 码点。",
		},
		{
			ID:          "go-027",
			Language:    quizLanguageGo,
			Prompt:      "Go 中适合保存 true 或 false 的类型是什么？",
			Options:     [4]string{"bool", "boolean", "truth", "bit"},
			AnswerIndex: 0,
			Explanation: "Go 使用 bool 类型保存布尔值。",
		},
		{
			ID:          "go-028",
			Language:    quizLanguageGo,
			Prompt:      "已有 map 变量 scores，怎样删除键 \"蓝妹\"？",
			Options:     [4]string{"scores.remove(\"蓝妹\")", "delete(scores, \"蓝妹\")", "remove(scores[\"蓝妹\"])", "scores[\"蓝妹\"] = delete"},
			AnswerIndex: 1,
			Explanation: "Go 使用内置函数 delete 从 map 中删除指定键。",
		},
		{
			ID:          "go-029",
			Language:    quizLanguageGo,
			Prompt:      "Go 中想忽略一个不需要的返回值，通常使用哪个标识符？",
			Options:     [4]string{"?", "ignore", "_", "nil"},
			AnswerIndex: 2,
			Explanation: "下划线 _ 是空白标识符，可用于接收并忽略值。",
		},
		{
			ID:          "go-030",
			Language:    quizLanguageGo,
			Prompt:      "已有 type Counter struct { Value int }，哪一项为 Counter 定义了 Get 方法？",
			Options:     [4]string{"method Counter.Get() int { return Value }", "func Counter.Get() int { return Counter.Value }", "func Get(c Counter) method int { return c.Value }", "func (c Counter) Get() int { return c.Value }"},
			AnswerIndex: 3,
			Explanation: "Go 方法在 func 后、方法名前写接收者，例如 (c Counter)。",
		},
	},
	quizLanguagePython: {
		{
			ID:          "python-001",
			Language:    quizLanguagePython,
			Prompt:      "Python 3 中哪一项可以输出文字 Hello？",
			Options:     [4]string{"echo \"Hello\"", "print(\"Hello\")", "fmt.Println(\"Hello\")", "System.out.println(\"Hello\")"},
			AnswerIndex: 1,
			Explanation: "Python 3 使用 print 函数输出内容。",
		},
		{
			ID:          "python-002",
			Language:    quizLanguagePython,
			Prompt:      "Python 主要用什么来表示 if、for、函数等代码块的范围？",
			Options:     [4]string{"花括号", "圆括号", "缩进", "分号"},
			AnswerIndex: 2,
			Explanation: "Python 通常在冒号后使用一致的缩进组织代码块。",
		},
		{
			ID:          "python-003",
			Language:    quizLanguagePython,
			Prompt:      "下面哪一项是 Python 列表？",
			Options:     [4]string{"(1, 2, 3)", "{1, 2, 3}", "<1, 2, 3>", "[1, 2, 3]"},
			AnswerIndex: 3,
			Explanation: "Python 列表使用方括号，例如 [1, 2, 3]。",
		},
		{
			ID:          "python-004",
			Language:    quizLanguagePython,
			Prompt:      "list(range(3)) 的结果是什么？",
			Options:     [4]string{"[0, 1, 2]", "[1, 2, 3]", "[0, 1, 2, 3]", "[3]"},
			AnswerIndex: 0,
			Explanation: "range(3) 从 0 开始，在到达 3 前停止。",
		},
		{
			ID:          "python-005",
			Language:    quizLanguagePython,
			Prompt:      "Python 中比较两个值是否相等，应使用哪个运算符？",
			Options:     [4]string{"=", "==", "===", ":="},
			AnswerIndex: 1,
			Explanation: "== 用于比较，= 用于赋值。",
		},
		{
			ID:          "python-006",
			Language:    quizLanguagePython,
			Prompt:      "Python 使用哪个关键字定义函数？",
			Options:     [4]string{"func", "function", "def", "fn"},
			AnswerIndex: 2,
			Explanation: "Python 函数定义以 def 关键字开始。",
		},
		{
			ID:          "python-007",
			Language:    quizLanguagePython,
			Prompt:      "Python 单行注释通常以哪个符号开头？",
			Options:     [4]string{"//", "--", ";", "#"},
			AnswerIndex: 3,
			Explanation: "# 后面的内容会被视为单行注释。",
		},
		{
			ID:          "python-008",
			Language:    quizLanguagePython,
			Prompt:      "len([\"a\", \"b\", \"c\"]) 的结果是什么？",
			Options:     [4]string{"3", "2", "4", "0"},
			AnswerIndex: 0,
			Explanation: "列表中有三个元素，所以 len 返回 3。",
		},
		{
			ID:          "python-009",
			Language:    quizLanguagePython,
			Prompt:      "下面哪一项是包含 name 键的 Python 字典？",
			Options:     [4]string{"[\"name\", \"Lanmei\"]", "{\"name\": \"Lanmei\"}", "(\"name\" = \"Lanmei\")", "<\"name\": \"Lanmei\">"},
			AnswerIndex: 1,
			Explanation: "字典使用花括号，并用冒号分隔键和值。",
		},
		{
			ID:          "python-010",
			Language:    quizLanguagePython,
			Prompt:      "已有 numbers = [1, 2]，怎样把 3 添加到列表末尾？",
			Options:     [4]string{"numbers.add(3)", "numbers.push(3)", "numbers.append(3)", "append(numbers, 3)"},
			AnswerIndex: 2,
			Explanation: "列表的 append 方法会在末尾添加一个元素。",
		},
		{
			ID:          "python-011",
			Language:    quizLanguagePython,
			Prompt:      "Python 表达式 7 // 2 的结果是什么？",
			Options:     [4]string{"3", "3.5", "4", "2"},
			AnswerIndex: 0,
			Explanation: "// 表示向下取整除法，7 // 2 的结果是 3。",
		},
		{
			ID:          "python-012",
			Language:    quizLanguagePython,
			Prompt:      "Python 3 的 input() 默认返回什么类型的值？",
			Options:     [4]string{"int", "str", "float", "bool"},
			AnswerIndex: 1,
			Explanation: "input() 读取的内容默认是字符串，需要时可再转换类型。",
		},
		{
			ID:          "python-013",
			Language:    quizLanguagePython,
			Prompt:      "下面哪个是 Python 中正确的布尔真值？",
			Options:     [4]string{"true", "TRUE", "True", "yes"},
			AnswerIndex: 2,
			Explanation: "Python 的布尔值写作 True 和 False，首字母需要大写。",
		},
		{
			ID:          "python-014",
			Language:    quizLanguagePython,
			Prompt:      "怎样判断字符串 name 是否在列表 names 中？",
			Options:     [4]string{"contains(names, name)", "name inside names", "names.has(name)", "name in names"},
			AnswerIndex: 3,
			Explanation: "in 运算符用于判断一个值是否属于容器。",
		},
		{
			ID:          "python-015",
			Language:    quizLanguagePython,
			Prompt:      "Python 中表示逻辑“并且”的关键字是什么？",
			Options:     [4]string{"and", "&&", "AND", "with"},
			AnswerIndex: 0,
			Explanation: "Python 使用 and 表示逻辑与。",
		},
		{
			ID:          "python-016",
			Language:    quizLanguagePython,
			Prompt:      "下面哪一项创建了一个元组？",
			Options:     [4]string{"[1, 2]", "(1, 2)", "{1, 2}", "<1, 2>"},
			AnswerIndex: 1,
			Explanation: "元组通常使用圆括号书写，例如 (1, 2)。",
		},
		{
			ID:          "python-017",
			Language:    quizLanguagePython,
			Prompt:      "len({1, 1, 2}) 的结果是什么？",
			Options:     [4]string{"3", "1", "2", "0"},
			AnswerIndex: 2,
			Explanation: "集合会去除重复元素，因此集合中只有 1 和 2 两个元素。",
		},
		{
			ID:          "python-018",
			Language:    quizLanguagePython,
			Prompt:      "已有 person = {\"name\": \"Lanmei\"}，怎样取得 name 对应的值？",
			Options:     [4]string{"person.name", "person(name)", "person->name", "person[\"name\"]"},
			AnswerIndex: 3,
			Explanation: "字典可以使用方括号和键读取对应的值。",
		},
		{
			ID:          "python-019",
			Language:    quizLanguagePython,
			Prompt:      "已有 name = \"蓝妹\"，哪一项是包含该变量值的 f-string？",
			Options:     [4]string{"f\"你好，{name}\"", "\"你好，${name}\"", "format\"你好，name\"", "f(\"你好\", name)"},
			AnswerIndex: 0,
			Explanation: "f-string 在字符串前加 f，并在花括号中写表达式。",
		},
		{
			ID:          "python-020",
			Language:    quizLanguagePython,
			Prompt:      "Python 中通常使用哪组关键字捕获并处理异常？",
			Options:     [4]string{"catch / throw", "try / except", "begin / rescue", "check / error"},
			AnswerIndex: 1,
			Explanation: "可能出错的代码写在 try 中，异常处理写在 except 中。",
		},
		{
			ID:          "python-021",
			Language:    quizLanguagePython,
			Prompt:      "执行 import math 后，哪一项可以计算 9 的平方根？",
			Options:     [4]string{"sqrt.math(9)", "math.root(9)", "math.sqrt(9)", "root(9)"},
			AnswerIndex: 2,
			Explanation: "math 模块中的 sqrt 函数用于计算平方根。",
		},
		{
			ID:          "python-022",
			Language:    quizLanguagePython,
			Prompt:      "已有 values = [10, 20, 30]，哪个表达式取得最后一个元素？",
			Options:     [4]string{"values[3]", "values[last]", "values.last()", "values[-1]"},
			AnswerIndex: 3,
			Explanation: "Python 序列的下标 -1 表示最后一个元素。",
		},
		{
			ID:          "python-023",
			Language:    quizLanguagePython,
			Prompt:      "已有 values = [0, 1, 2, 3]，values[1:3] 的结果是什么？",
			Options:     [4]string{"[1, 2]", "[1, 2, 3]", "[0, 1, 2]", "[2, 3]"},
			AnswerIndex: 0,
			Explanation: "切片包含起始下标 1，不包含结束下标 3，因此得到 [1, 2]。",
		},
		{
			ID:          "python-024",
			Language:    quizLanguagePython,
			Prompt:      "哪一项可以依次遍历列表 items 中的元素？",
			Options:     [4]string{"for (item : items):", "for item in items:", "foreach item items:", "loop item from items:"},
			AnswerIndex: 1,
			Explanation: "Python 使用 for 变量 in 可迭代对象: 的形式遍历元素。",
		},
		{
			ID:          "python-025",
			Language:    quizLanguagePython,
			Prompt:      "哪个关键字用于在条件为真时重复执行代码？",
			Options:     [4]string{"repeat", "loop", "while", "until"},
			AnswerIndex: 2,
			Explanation: "while 循环会在条件为真时反复执行代码块。",
		},
		{
			ID:          "python-026",
			Language:    quizLanguagePython,
			Prompt:      "哪一项正确定义了一个空的 Student 类？",
			Options:     [4]string{"class Student {}", "type Student:", "Student = class()", "class Student:\n    pass"},
			AnswerIndex: 3,
			Explanation: "Python 使用 class 定义类；空类体可以写 pass。",
		},
		{
			ID:          "python-027",
			Language:    quizLanguagePython,
			Prompt:      "Python 类中，实例初始化方法通常叫什么？",
			Options:     [4]string{"__init__", "constructor", "initialize", "__new_object__"},
			AnswerIndex: 0,
			Explanation: "创建实例后，Python 通常调用 __init__ 方法初始化实例。",
		},
		{
			ID:          "python-028",
			Language:    quizLanguagePython,
			Prompt:      "Python 中表示“没有值”的特殊对象是什么？",
			Options:     [4]string{"null", "None", "nil", "undefined"},
			AnswerIndex: 1,
			Explanation: "Python 使用 None 表示没有具体值。",
		},
		{
			ID:          "python-029",
			Language:    quizLanguagePython,
			Prompt:      "哪一项可以把整数 42 转换成字符串？",
			Options:     [4]string{"string(42)", "42.toString()", "str(42)", "text(42)"},
			AnswerIndex: 2,
			Explanation: "内置 str 函数可以把整数转换为字符串。",
		},
		{
			ID:          "python-030",
			Language:    quizLanguagePython,
			Prompt:      "sum([1, 2, 3]) 的结果是什么？",
			Options:     [4]string{"3", "5", "123", "6"},
			AnswerIndex: 3,
			Explanation: "sum 会把序列中的数相加，1 + 2 + 3 等于 6。",
		},
	},
	quizLanguageC: {
		{
			ID:          "c-001",
			Language:    quizLanguageC,
			Prompt:      "C 程序使用 printf 前，通常需要包含哪个头文件？",
			Options:     [4]string{"<stdio.h>", "<string.h>", "<math.h>", "<stdlib.h>"},
			AnswerIndex: 0,
			Explanation: "printf 声明在标准输入输出头文件 stdio.h 中。",
		},
		{
			ID:          "c-002",
			Language:    quizLanguageC,
			Prompt:      "C 中哪一项可以输出整数变量 age 的值？",
			Options:     [4]string{"print(age);", "printf(\"%d\", age);", "cout << age;", "fmt.Println(age);"},
			AnswerIndex: 1,
			Explanation: "printf 的 %d 格式说明符可输出 int 值。",
		},
		{
			ID:          "c-003",
			Language:    quizLanguageC,
			Prompt:      "标准 C 程序入口通常写成哪一项？",
			Options:     [4]string{"void start()", "func main()", "int main(void)", "def main():"},
			AnswerIndex: 2,
			Explanation: "int main(void) 是不接收参数时的标准入口写法之一。",
		},
		{
			ID:          "c-004",
			Language:    quizLanguageC,
			Prompt:      "C 中大多数简单语句末尾使用什么符号？",
			Options:     [4]string{"冒号", "逗号", "句号", "分号"},
			AnswerIndex: 3,
			Explanation: "C 的声明、赋值和函数调用等语句通常以分号结束。",
		},
		{
			ID:          "c-005",
			Language:    quizLanguageC,
			Prompt:      "若 int numbers[3] = {10, 20, 30};，第一个元素是哪个？",
			Options:     [4]string{"numbers[0]", "numbers[1]", "numbers.first", "numbers(0)"},
			AnswerIndex: 0,
			Explanation: "C 数组下标从 0 开始。",
		},
		{
			ID:          "c-006",
			Language:    quizLanguageC,
			Prompt:      "C 中表示逻辑“并且”的运算符是哪一个？",
			Options:     [4]string{"||", "&&", "&=", "!"},
			AnswerIndex: 1,
			Explanation: "&& 是逻辑与运算符。",
		},
		{
			ID:          "c-007",
			Language:    quizLanguageC,
			Prompt:      "已有 int x = 10;，哪个表达式可以取得 x 的地址？",
			Options:     [4]string{"*x", "@x", "&x", "#x"},
			AnswerIndex: 2,
			Explanation: "一元运算符 & 用于取得对象的地址。",
		},
		{
			ID:          "c-008",
			Language:    quizLanguageC,
			Prompt:      "下面哪一项声明了一个指向 int 的指针 p？",
			Options:     [4]string{"pointer<int> p;", "int &p;", "ptr int p;", "int *p;"},
			AnswerIndex: 3,
			Explanation: "int *p 声明 p 为指向 int 的指针。",
		},
		{
			ID:          "c-009",
			Language:    quizLanguageC,
			Prompt:      "C 中通常使用哪种类型保存单个字符？",
			Options:     [4]string{"char", "string", "text", "byte[]"},
			AnswerIndex: 0,
			Explanation: "char 用于保存一个字符值。",
		},
		{
			ID:          "c-010",
			Language:    quizLanguageC,
			Prompt:      "下面循环会依次输出什么？\nfor (int i = 1; i <= 3; i++) {\n    printf(\"%d\", i);\n}",
			Options:     [4]string{"012", "123", "1234", "321"},
			AnswerIndex: 1,
			Explanation: "i 从 1 增加到 3，依次输出 123。",
		},
		{
			ID:          "c-011",
			Language:    quizLanguageC,
			Prompt:      "执行 int result = 7 / 2; 后，result 的值是多少？",
			Options:     [4]string{"3", "3.5", "4", "2"},
			AnswerIndex: 0,
			Explanation: "两个 int 相除会进行整数除法，小数部分被舍去，因此结果为 3。",
		},
		{
			ID:          "c-012",
			Language:    quizLanguageC,
			Prompt:      "已有 int age;，哪一项可以用 scanf 读取 age？",
			Options:     [4]string{"scanf(\"%d\", age);", "scanf(\"%d\", &age);", "scanf(age, \"%d\");", "read(&age);"},
			AnswerIndex: 1,
			Explanation: "scanf 使用 %d 读取 int，并需要传入变量 age 的地址 &age。",
		},
		{
			ID:          "c-013",
			Language:    quizLanguageC,
			Prompt:      "在声明 int values[4]; 的同一作用域中，哪一项可计算数组元素个数？",
			Options:     [4]string{"sizeof(values)", "length(values)", "sizeof(values) / sizeof(values[0])", "values.size"},
			AnswerIndex: 2,
			Explanation: "整个数组的字节数除以一个元素的字节数，可以得到元素个数。",
		},
		{
			ID:          "c-014",
			Language:    quizLanguageC,
			Prompt:      "包含 <string.h> 后，strlen(\"cat\") 的结果是什么？",
			Options:     [4]string{"4", "2", "取决于平台", "3"},
			AnswerIndex: 3,
			Explanation: "strlen 返回终止空字符之前的字符数量，因此结果为 3。",
		},
		{
			ID:          "c-015",
			Language:    quizLanguageC,
			Prompt:      "包含 <string.h> 后，strcmp(a, b) 返回什么值表示两个字符串内容相同？",
			Options:     [4]string{"0", "1", "-1", "true"},
			AnswerIndex: 0,
			Explanation: "strcmp 在两个字符串内容相同时返回 0。",
		},
		{
			ID:          "c-016",
			Language:    quizLanguageC,
			Prompt:      "C 中常用哪个宏表示空指针常量？",
			Options:     [4]string{"None", "NULL", "nil", "empty"},
			AnswerIndex: 1,
			Explanation: "NULL 是标准头文件中定义的空指针常量宏。",
		},
		{
			ID:          "c-017",
			Language:    quizLanguageC,
			Prompt:      "已有 int value = 8; int *p = &value;，哪个表达式取得 p 指向的值？",
			Options:     [4]string{"&p", "p.value", "*p", "p->value"},
			AnswerIndex: 2,
			Explanation: "一元 * 运算符解引用指针，得到它指向的对象。",
		},
		{
			ID:          "c-018",
			Language:    quizLanguageC,
			Prompt:      "哪一项定义了一个接收两个 int 并返回 int 的 add 函数？",
			Options:     [4]string{"func add(a, b int) int", "def add(a, b):", "function int add(a, b)", "int add(int a, int b) { return a + b; }"},
			AnswerIndex: 3,
			Explanation: "C 函数定义需要写返回类型、函数名、带类型的参数和函数体。",
		},
		{
			ID:          "c-019",
			Language:    quizLanguageC,
			Prompt:      "哪一项声明了不能通过变量名 maxCount 修改的整数？",
			Options:     [4]string{"const int maxCount = 10;", "fixed int maxCount = 10;", "readonly maxCount = 10;", "int constant maxCount = 10;"},
			AnswerIndex: 0,
			Explanation: "const 修饰的对象不能通过该变量名再次修改。",
		},
		{
			ID:          "c-020",
			Language:    quizLanguageC,
			Prompt:      "使用 malloc 和 free 通常需要包含哪个标准头文件？",
			Options:     [4]string{"<stdio.h>", "<stdlib.h>", "<string.h>", "<memory.h>"},
			AnswerIndex: 1,
			Explanation: "malloc 和 free 声明在 stdlib.h 中。",
		},
		{
			ID:          "c-021",
			Language:    quizLanguageC,
			Prompt:      "由 int *p = malloc(sizeof(int)); 获得的内存不再使用时，应调用什么？",
			Options:     [4]string{"delete p;", "release(p);", "free(p);", "clear(p);"},
			AnswerIndex: 2,
			Explanation: "malloc 分配的内存应使用 free 释放。",
		},
		{
			ID:          "c-022",
			Language:    quizLanguageC,
			Prompt:      "哪一项定义了包含 int age; 成员的结构体 Student？",
			Options:     [4]string{"class Student { int age; };", "record Student (int age);", "Student = { age: int };", "struct Student { int age; };"},
			AnswerIndex: 3,
			Explanation: "C 使用 struct 关键字定义结构体。",
		},
		{
			ID:          "c-023",
			Language:    quizLanguageC,
			Prompt:      "typedef unsigned int uint; 的作用是什么？",
			Options:     [4]string{"为 unsigned int 创建别名 uint", "声明一个名为 uint 的变量", "把 uint 转换为 int", "定义一个函数"},
			AnswerIndex: 0,
			Explanation: "typedef 可以为已有类型创建新的类型别名。",
		},
		{
			ID:          "c-024",
			Language:    quizLanguageC,
			Prompt:      "哪一项创建了内容为 Hi、且可修改内容的字符数组 text？",
			Options:     [4]string{"char text = \"Hi\";", "char text[] = \"Hi\";", "string text = \"Hi\";", "char[] text = \"Hi\";"},
			AnswerIndex: 1,
			Explanation: "char text[] = \"Hi\" 会创建包含 H、i 和终止空字符的可修改数组。",
		},
		{
			ID:          "c-025",
			Language:    quizLanguageC,
			Prompt:      "在 switch 的 case 中，哪个关键字常用于避免继续执行后续 case？",
			Options:     [4]string{"stop", "exit", "break", "next"},
			AnswerIndex: 2,
			Explanation: "break 会结束当前 switch，避免继续落入后续 case。",
		},
		{
			ID:          "c-026",
			Language:    quizLanguageC,
			Prompt:      "哪种循环即使条件一开始为假，也会先执行一次循环体？",
			Options:     [4]string{"for", "while", "foreach", "do ... while"},
			AnswerIndex: 3,
			Explanation: "do ... while 在循环体执行后才检查条件，因此至少执行一次。",
		},
		{
			ID:          "c-027",
			Language:    quizLanguageC,
			Prompt:      "哪一项使用预处理器定义了值为 100 的宏 MAX_SIZE？",
			Options:     [4]string{"#define MAX_SIZE 100", "const MAX_SIZE = 100", "macro MAX_SIZE 100", "#set MAX_SIZE 100"},
			AnswerIndex: 0,
			Explanation: "#define 指令可以定义对象式宏。",
		},
		{
			ID:          "c-028",
			Language:    quizLanguageC,
			Prompt:      "C 的条件运算符（三元运算符）使用哪组符号？",
			Options:     [4]string{"if : else", "? :", "=> :", "?? ::"},
			AnswerIndex: 1,
			Explanation: "条件表达式写作 条件 ? 真值 : 假值。",
		},
		{
			ID:          "c-029",
			Language:    quizLanguageC,
			Prompt:      "循环中的 continue 语句通常会做什么？",
			Options:     [4]string{"结束整个程序", "退出当前函数", "跳过本次循环剩余部分并进入下一次迭代", "重新开始整个程序"},
			AnswerIndex: 2,
			Explanation: "continue 跳过当前迭代剩余语句，继续下一次循环。",
		},
		{
			ID:          "c-030",
			Language:    quizLanguageC,
			Prompt:      "在 main 函数末尾执行 return 0; 通常表示什么？",
			Options:     [4]string{"输出数字 0", "程序暂停", "重新运行 main", "程序正常结束"},
			AnswerIndex: 3,
			Explanation: "main 返回 0 通常向运行环境表示程序成功结束。",
		},
	},
	quizLanguageCPP: {
		{
			ID:          "cpp-001",
			Language:    quizLanguageCPP,
			Prompt:      "C++ 使用 std::cout 前，通常需要包含哪个头文件？",
			Options:     [4]string{"<stdio.h>", "<vector>", "<iostream>", "<string>"},
			AnswerIndex: 2,
			Explanation: "std::cout 定义在 iostream 头文件中。",
		},
		{
			ID:          "cpp-002",
			Language:    quizLanguageCPP,
			Prompt:      "包含 <iostream> 后，哪一项可以输出 Hello？",
			Options:     [4]string{"printfLine(\"Hello\");", "System.out.println(\"Hello\");", "print(\"Hello\");", "std::cout << \"Hello\";"},
			AnswerIndex: 3,
			Explanation: "C++ 可使用 std::cout 和 << 输出内容。",
		},
		{
			ID:          "cpp-003",
			Language:    quizLanguageCPP,
			Prompt:      "表达式 std::cout 中的 std 表示什么？",
			Options:     [4]string{"标准库使用的命名空间", "一种整数类型", "循环关键字", "文件扩展名"},
			AnswerIndex: 0,
			Explanation: "std 是 C++ 标准库使用的命名空间名称。",
		},
		{
			ID:          "cpp-004",
			Language:    quizLanguageCPP,
			Prompt:      "C++ 使用哪个关键字定义类？",
			Options:     [4]string{"object", "class", "type", "structOnly"},
			AnswerIndex: 1,
			Explanation: "class 关键字用于定义类。",
		},
		{
			ID:          "cpp-005",
			Language:    quizLanguageCPP,
			Prompt:      "包含 <string> 后，哪种类型适合保存一段文本？",
			Options:     [4]string{"char", "text", "std::string", "words"},
			AnswerIndex: 2,
			Explanation: "std::string 是标准库提供的字符串类型。",
		},
		{
			ID:          "cpp-006",
			Language:    quizLanguageCPP,
			Prompt:      "包含 <vector> 后，哪一项声明了一个可变长度的整数序列？",
			Options:     [4]string{"int values();", "list values<int>;", "int[] values;", "std::vector<int> values;"},
			AnswerIndex: 3,
			Explanation: "std::vector<int> 是可动态改变长度的整数序列。",
		},
		{
			ID:          "cpp-007",
			Language:    quizLanguageCPP,
			Prompt:      "C++ 中适合保存 true 或 false 的类型是什么？",
			Options:     [4]string{"bool", "boolean", "bit", "truth"},
			AnswerIndex: 0,
			Explanation: "C++ 使用 bool 类型保存布尔值。",
		},
		{
			ID:          "cpp-008",
			Language:    quizLanguageCPP,
			Prompt:      "C++ 单行注释通常以哪个符号开头？",
			Options:     [4]string{"#", "//", "--", ";;"},
			AnswerIndex: 1,
			Explanation: "// 后面的内容会被视为单行注释。",
		},
		{
			ID:          "cpp-009",
			Language:    quizLanguageCPP,
			Prompt:      "C++ 中比较两个值是否相等，应使用哪个运算符？",
			Options:     [4]string{"=", "===", "==", ":="},
			AnswerIndex: 2,
			Explanation: "== 用于相等比较，= 用于赋值。",
		},
		{
			ID:          "cpp-010",
			Language:    quizLanguageCPP,
			Prompt:      "下面循环会依次输出什么？\nfor (int i = 0; i < 3; i++) {\n    std::cout << i;\n}",
			Options:     [4]string{"123", "0123", "321", "012"},
			AnswerIndex: 3,
			Explanation: "i 依次为 0、1、2，因此输出 012。",
		},
		{
			ID:          "cpp-011",
			Language:    quizLanguageCPP,
			Prompt:      "执行 int result = 7 / 2; 后，result 的值是多少？",
			Options:     [4]string{"3", "3.5", "4", "2"},
			AnswerIndex: 0,
			Explanation: "两个 int 相除会进行整数除法，小数部分被舍去，因此结果为 3。",
		},
		{
			ID:          "cpp-012",
			Language:    quizLanguageCPP,
			Prompt:      "包含 <iostream> 后，哪一项可以从标准输入读取整数 age？",
			Options:     [4]string{"std::cout >> age;", "std::cin >> age;", "input(age);", "scanf(age);"},
			AnswerIndex: 1,
			Explanation: "std::cin 配合 >> 运算符可以从标准输入读取值。",
		},
		{
			ID:          "cpp-013",
			Language:    quizLanguageCPP,
			Prompt:      "已有 std::vector<int> values{1, 2, 3};，怎样取得元素数量？",
			Options:     [4]string{"values.length", "len(values)", "values.size()", "sizeof(values)"},
			AnswerIndex: 2,
			Explanation: "std::vector 的 size() 成员函数返回当前元素数量。",
		},
		{
			ID:          "cpp-014",
			Language:    quizLanguageCPP,
			Prompt:      "若 std::vector<int> values{10, 20};，怎样取得第一个元素？",
			Options:     [4]string{"values(0)", "values[1]", "values.first()", "values[0]"},
			AnswerIndex: 3,
			Explanation: "vector 与数组一样从下标 0 开始访问元素。",
		},
		{
			ID:          "cpp-015",
			Language:    quizLanguageCPP,
			Prompt:      "哪一项是合法的 C++ 条件判断写法？",
			Options:     [4]string{"if (score >= 60) { }", "if score >= 60 then", "when score >= 60 { }", "if score >= 60:"},
			AnswerIndex: 0,
			Explanation: "C++ 的 if 条件写在圆括号中，代码块通常写在花括号中。",
		},
		{
			ID:          "cpp-016",
			Language:    quizLanguageCPP,
			Prompt:      "C++ 中表示逻辑“或者”的运算符是哪一个？",
			Options:     [4]string{"&&", "||", "or=", "|="},
			AnswerIndex: 1,
			Explanation: "|| 是逻辑或运算符，只要一侧为 true，结果通常就是 true。",
		},
		{
			ID:          "cpp-017",
			Language:    quizLanguageCPP,
			Prompt:      "哪一项定义了一个接收两个 int 并返回 int 的 add 函数？",
			Options:     [4]string{"func add(a, b int) int", "def add(a, b):", "int add(int a, int b) { return a + b; }", "function int add(a, b)"},
			AnswerIndex: 2,
			Explanation: "C++ 函数定义需要写返回类型、函数名、带类型的参数和函数体。",
		},
		{
			ID:          "cpp-018",
			Language:    quizLanguageCPP,
			Prompt:      "已有 int value = 5;，哪一项声明了 value 的引用 ref？",
			Options:     [4]string{"int *ref = value;", "ref int = value;", "int ref* = value;", "int &ref = value;"},
			AnswerIndex: 3,
			Explanation: "int &ref = value 声明 ref 为 value 的左值引用。",
		},
		{
			ID:          "cpp-019",
			Language:    quizLanguageCPP,
			Prompt:      "哪一项声明了初始化后不能被重新赋值的整数 maxCount？",
			Options:     [4]string{"const int maxCount = 10;", "fixed int maxCount = 10;", "readonly maxCount = 10;", "int constant maxCount = 10;"},
			AnswerIndex: 0,
			Explanation: "const 修饰的对象不能通过该名称再次修改。",
		},
		{
			ID:          "cpp-020",
			Language:    quizLanguageCPP,
			Prompt:      "C++11 起，推荐用哪个空指针字面量？",
			Options:     [4]string{"nil", "nullptr", "None", "empty"},
			AnswerIndex: 1,
			Explanation: "nullptr 是 C++11 引入的类型安全空指针字面量。",
		},
		{
			ID:          "cpp-021",
			Language:    quizLanguageCPP,
			Prompt:      "std::cout << \"Hello\" << std::endl; 中 std::endl 的主要作用是什么？",
			Options:     [4]string{"结束程序", "清空字符串", "换行并刷新输出缓冲区", "读取一行"},
			AnswerIndex: 2,
			Explanation: "std::endl 会插入换行符，并刷新输出缓冲区。",
		},
		{
			ID:          "cpp-022",
			Language:    quizLanguageCPP,
			Prompt:      "执行 auto count = 42; 时，count 通常会被推导为什么类型？",
			Options:     [4]string{"double", "std::string", "bool", "int"},
			AnswerIndex: 3,
			Explanation: "整数字面量 42 默认是 int，因此 auto 会把 count 推导为 int。",
		},
		{
			ID:          "cpp-023",
			Language:    quizLanguageCPP,
			Prompt:      "已有 std::vector<int> values，哪一项可以依次遍历其中的每个整数？",
			Options:     [4]string{"for (int value : values) { }", "for value in values { }", "foreach value values { }", "loop (values as value) { }"},
			AnswerIndex: 0,
			Explanation: "范围 for 循环使用 for (元素声明 : 容器) 的形式。",
		},
		{
			ID:          "cpp-024",
			Language:    quizLanguageCPP,
			Prompt:      "在 class 定义中，哪个访问说明符让后续成员可以从类外访问？",
			Options:     [4]string{"open:", "public:", "export:", "global:"},
			AnswerIndex: 1,
			Explanation: "public: 后的成员可以在符合其他规则时从类外访问。",
		},
		{
			ID:          "cpp-025",
			Language:    quizLanguageCPP,
			Prompt:      "若已有 class Animal {};，哪一项表示 Dog 公有继承 Animal？",
			Options:     [4]string{"class Dog inherits Animal {};", "class Dog(Animal) {};", "class Dog : public Animal {};", "class Dog extends Animal {};"},
			AnswerIndex: 2,
			Explanation: "C++ 使用冒号和 public 指定公有继承。",
		},
		{
			ID:          "cpp-026",
			Language:    quizLanguageCPP,
			Prompt:      "类名为 Student 时，它的构造函数名称是什么？",
			Options:     [4]string{"new", "constructor", "init", "Student"},
			AnswerIndex: 3,
			Explanation: "构造函数与类同名，并且不写返回类型。",
		},
		{
			ID:          "cpp-027",
			Language:    quizLanguageCPP,
			Prompt:      "类名为 Student 时，析构函数应写成哪一项？",
			Options:     [4]string{"~Student()", "delete Student()", "Student~()", "destroy Student()"},
			AnswerIndex: 0,
			Explanation: "析构函数名称是在类名前加波浪号，例如 ~Student()。",
		},
		{
			ID:          "cpp-028",
			Language:    quizLanguageCPP,
			Prompt:      "向 std::vector<int> values 的末尾添加 5，应使用哪一项？",
			Options:     [4]string{"values.append(5);", "values.push_back(5);", "values.add(5);", "push(values, 5);"},
			AnswerIndex: 1,
			Explanation: "vector 的 push_back 会在末尾添加一个元素。",
		},
		{
			ID:          "cpp-029",
			Language:    quizLanguageCPP,
			Prompt:      "在 switch 的 case 中，哪个关键字常用于结束当前分支，避免继续执行后续 case？",
			Options:     [4]string{"stop", "exit", "break", "returnCase"},
			AnswerIndex: 2,
			Explanation: "break 会结束当前 switch，避免继续落入后续 case。",
		},
		{
			ID:          "cpp-030",
			Language:    quizLanguageCPP,
			Prompt:      "动态创建的 int* value = new int(5); 不再使用时，应该怎样释放？",
			Options:     [4]string{"free(value);", "remove value;", "clear(value);", "delete value;"},
			AnswerIndex: 3,
			Explanation: "由 new 创建的单个对象应使用 delete 释放。",
		},
	},
}
